version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flatshare-db
    environment:
      POSTGRES_USER: flatshare_user
      POSTGRES_PASSWORD: flatshare_password
      POSTGRES_DB: flatshare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://flatshare_user:flatshare_password@postgres:5432/flatshare_db?sslmode=disable
    depends_on:
      - postgres
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: flatshare-azurite
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  azurite_data: